apiVersion: apps/v1
kind: Deployment
metadata:
  name: mkloiu
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mkloiu
  template:
    metadata:
      labels:
        app: mkloiu
    spec:
      containers:
      - image: okteto.dev/seiodck:latest
        name: mkloiu
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        - name: ProxySite
          value: "mirror.umd.edu"
        - name: Vless_UUID
          value: "40d30eb4-6923-4649-9323-95e652e6cc85"
        - name: Vless_Path
          value: "/40d30eb4-6923-4649-9323-95e652e6cc85-vless"
        - name: Vmess_UUID
          value: "3feea69d-e03d-4f64-8f57-91381020a73c"
        - name: Vmess_Path
          value: "/3feea69d-e03d-4f64-8f57-91381020a73c-vmess"
        - name: Share_Path
          value: "$Share_Path"
